### ISSUE TITLE
Consider removing decimals

### ISSUE THREAD

**Issue by kosecki123** [chronologic/debt-smart-contract#12]
When setting different decimals than 18 (which is ETH decimals), the exchangeRate has to take this into calculations. 

Since there is no benefit of having other decimal numbers than 18, we should make it as default, not configurable setting.

**Comment by adibas03** [comment]
Implemented https://github.com/chronologic/debt-smart-contract/commit/38a302652039dfd8e911e1e53ff15943c1f85299
